print('---------- 1º pessoa ----------')
n1 = str(input('Nome: '))
i1 = int(input('Idade: '))
s1 = str(input('Sexo F/M: '))
print('---------- 2º pessoa ----------')
n2 = str(input('Nome: '))
i2 = int(input('Idade: '))
s2 = str(input('Sexo F/M: '))
print('---------- 3º pessoa ----------')
n3 = str(input('Nome: '))
i3 = int(input('Idade: '))
s3 = str(input('Sexo F/M: '))
print('---------- 4º pessoa ----------')
n4 = str(input('Nome: '))
i4 = int(input('Idade: '))
s4 = str(input('Sexo F/M: '))
print('-------------------------------')
print('A idade média do grupo é {}'.format((i1 + i2 + i3 + i4) / 4))
