loja = ('Lápis', 1.75, 'Borracha', 2.00, 'Caderno', 15.90, 'Estojo', 25.00, 'Transferidor', 4.20)
print('------------------------')
print('         Preços         ')
print('------------------------')
print(f'{loja[0]}-------------R${loja[1]}')
print(f'{loja[2]}----------R${loja[3]}')
print()